apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: atxfinance-backend
  labels:
    app.kubernetes.io/name: atxfinance-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atxfinance-backend
