import { formatBackendSessionCookieHeader } from "@/lib/backend-session-cookie";
import { getAtxfinanceBackendOrigin } from "@/lib/env";

const STRATEGY_SYMBOL_PATTERN = /^[A-Z0-9.\-]{1,12}$/;
const PORTFOLIO_ID_PATTERN = /^[a-fA-F0-9]{24}$/;

type StrategyOutlook = "bullish" | "bearish" | "neutral";
type StrategyRisk = "conservative" | "moderate" | "aggressive";

const STRATEGY_OUTLOOKS = new Set<StrategyOutlook>(["bullish", "bearish", "neutral"]);
const STRATEGY_RISKS = new Set<StrategyRisk>(["conservative", "moderate", "aggressive"]);
const STRATEGY_KINDS = new Set([
  "covered_call",
  "cash_secured_put",
  "protective_put",
  "long_straddle",
  "wheel_protective_collar",
  "iron_condor",
  "bull_put_spread",
  "bear_call_spread",
  "long_call",
  "long_put"
]);

export type StrategyRecommendationsToolRequest = {
  portfolioId?: string;
  symbols: string[];
  outlook: StrategyOutlook;
  risk: StrategyRisk;
  horizonDays: number;
  preferredStrategies?: string[];
  maxResults: number;
  /** Local dev only: Spring may use synthetic chains when Yahoo is unavailable. */
  allowSyntheticFallback?: boolean;
  /** Engine fit floor (0–100). Hot Picks passes the UI edge slider value. */
  minScore?: number;
};

export type StrategyRecommendationsToolContext = {
  sessionCookie?: string;
  workspacePortfolioId?: string | null;
};

export type StrategyRecommendationsToolResult =
  | { ok: true; payload: unknown }
  | {
      ok: false;
      error: "invalid_strategy_context" | "engine_unavailable";
      message: string;
      details?: unknown;
    };

export function parseStrategyRecommendationsToolArgs(
  args: Record<string, unknown>,
  ctx: Pick<StrategyRecommendationsToolContext, "workspacePortfolioId"> = {}
): StrategyRecommendationsToolResult {
  const symbols = normalizeSymbols(args);
  const outlook = normalizeEnum(args.outlook, STRATEGY_OUTLOOKS);
  const risk = normalizeEnum(args.risk ?? args.riskTolerance, STRATEGY_RISKS);
  const horizonDays = normalizeInteger(args.horizonDays ?? args.daysToExpiration ?? args.dte);
  const portfolioId = normalizePortfolioId(args.portfolioId) ?? normalizePortfolioId(ctx.workspacePortfolioId);
  const preferredStrategies = normalizePreferredStrategies(args.preferredStrategies);
  const maxResults = normalizeInteger(args.maxResults) ?? 5;
  const minScore = normalizeInteger(args.minScore ?? args.minEdgeScore);

  if (symbols.length === 0 || outlook == null || risk == null || horizonDays == null) {
    return {
      ok: false,
      error: "invalid_strategy_context",
      message:
        "strategy_recommendations requires symbols, outlook, risk, and horizonDays before engine generation."
    };
  }

  if (horizonDays < 1 || horizonDays > 365) {
    return {
      ok: false,
      error: "invalid_strategy_context",
      message: "horizonDays must be between 1 and 365."
    };
  }

  const allowSyntheticFallback =
    args.allowSyntheticFallback === true ||
    (process.env.ATX_DEPLOY_TARGET?.trim().toLowerCase() === "dev" &&
      process.env.NODE_ENV !== "production");

  return {
    ok: true,
    payload: {
      ...(portfolioId ? { portfolioId } : {}),
      symbols,
      outlook,
      risk,
      horizonDays,
      ...(preferredStrategies.length > 0 ? { preferredStrategies } : {}),
      maxResults: Math.max(1, Math.min(10, maxResults)),
      ...(allowSyntheticFallback ? { allowSyntheticFallback: true } : {}),
      ...(minScore != null ? { minScore: Math.max(0, Math.min(100, minScore)) } : {})
    } satisfies StrategyRecommendationsToolRequest
  };
}

export async function runStrategyRecommendationsTool(
  args: Record<string, unknown>,
  ctx: StrategyRecommendationsToolContext
): Promise<unknown> {
  const parsed = parseStrategyRecommendationsToolArgs(args, ctx);
  if (!parsed.ok) {
    return {
      error: parsed.error,
      message: parsed.message,
      details: parsed.details
    };
  }

  const origin = getAtxfinanceBackendOrigin();
  if (!origin) {
    return {
      error: "engine_unavailable",
      message:
        "Strategy recommendations are generated by atxfinance-backend. Set ATXFINANCE_BACKEND_ORIGIN to enable this tool."
    };
  }
  const cookieHeader = formatBackendSessionCookieHeader(ctx.sessionCookie ?? "");
  if (!cookieHeader) {
    return {
      error: "engine_unavailable",
      message: "Missing session cookie for backend-scoped strategy recommendation generation."
    };
  }

  let response: Response;
  try {
    response = await fetch(`${origin}/api/strategy-recommendations/generate`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        cookie: cookieHeader
      },
      body: JSON.stringify(parsed.payload)
    });
  } catch {
    return {
      error: "engine_unavailable",
      message: "Strategy recommendation backend request failed."
    };
  }

  const body = await readJsonBody(response);
  if (!response.ok) {
    return {
      error: response.status === 400 ? "invalid_strategy_context" : "engine_unavailable",
      status: response.status,
      details: body
    };
  }

  return body;
}

function normalizeSymbols(args: Record<string, unknown>): string[] {
  const rawSymbols = Array.isArray(args.symbols)
    ? args.symbols
    : [args.symbol, args.underlying].filter((value): value is string => typeof value === "string");
  const normalized = rawSymbols
    .map((value) => (typeof value === "string" ? value.trim().toUpperCase() : ""))
    .filter((value) => STRATEGY_SYMBOL_PATTERN.test(value));
  return Array.from(new Set(normalized)).slice(0, 5);
}

function normalizeEnum<T extends string>(value: unknown, allowed: Set<T>): T | null {
  if (typeof value !== "string") {
    return null;
  }
  const normalized = value.trim().toLowerCase().replaceAll("-", "_") as T;
  return allowed.has(normalized) ? normalized : null;
}

function normalizeInteger(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) {
    return Math.trunc(value);
  }
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? Math.trunc(parsed) : null;
  }
  return null;
}

function normalizePortfolioId(value: unknown): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }
  const trimmed = value.trim();
  return PORTFOLIO_ID_PATTERN.test(trimmed) ? trimmed : undefined;
}

function normalizePreferredStrategies(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  const normalized = value
    .map((item) => normalizeEnum(item, STRATEGY_KINDS))
    .filter((item): item is string => item != null);
  return Array.from(new Set(normalized));
}

async function readJsonBody(response: Response): Promise<unknown> {
  try {
    return await response.json();
  } catch {
    return null;
  }
}
