services:
  mongodb:
    image: mongo:8
    container_name: atxfinance-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: atxfinancedb
    volumes:
      - atxfinance_mongo_data:/data/db

volumes:
  atxfinance_mongo_data:
