services:
  mongodb:
    image: mongo:8
    container_name: xfinance-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: xfinancedb
    volumes:
      - xfinance_mongo_data:/data/db

volumes:
  xfinance_mongo_data:
