/** Current advisor AI disclosure version — bump when copy changes materially. */
export const ADVISOR_AI_DISCLOSURE_VERSION = "2026-05-advisor-v1" as const;

/** Compact disclosure for forms and inline ack surfaces. */
export const ADVISOR_AI_DISCLOSURE_SHORT =
  "Outputs are generated by algorithmic and AI systems (including large language models). They may be incomplete, outdated, or incorrect. You remain responsible for suitability, best-interest obligations, and all client communications. This platform does not execute trades or establish an advisory relationship with your clients.";

/** Full disclosure shown before advisor compliance attestation. */
export const ADVISOR_AI_DISCLOSURE_FULL = `${ADVISOR_AI_DISCLOSURE_SHORT}

Limitations: Models do not have access to non-public information, real-time market data unless explicitly wired through approved tools, or your firm's full compliance policies. Recommendations are illustrative decision support — not a substitute for your independent professional judgment, supervisory review, or firm procedures.

By acknowledging, you confirm you will disclose the AI-assisted nature of relevant outputs to clients as required by your firm's policies and applicable regulations.`;

export type AdvisorAiDisclosureBundle = {
  version: typeof ADVISOR_AI_DISCLOSURE_VERSION;
  short: string;
  full: string;
};

export function getAdvisorAiDisclosureBundle(): AdvisorAiDisclosureBundle {
  return {
    version: ADVISOR_AI_DISCLOSURE_VERSION,
    short: ADVISOR_AI_DISCLOSURE_SHORT,
    full: ADVISOR_AI_DISCLOSURE_FULL
  };
}
