apiVersion: v1
kind: Service
metadata:
  name: atxfinance-backend
  labels:
    app.kubernetes.io/name: atxfinance-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atxfinance-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
